### ISSUE TITLE
Which gtkd to use / Vasaro in Ubuntu 16.04 ?

### ISSUE THREAD

**Issue by whplh** [trikko/vasaro#3]
I get the following warnings and then errors:
________

WARNING: A deprecated branch based version specification is used for the dependency derelict-sdl2. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
WARNING: A deprecated branch based version specification is used for the dependency derelict-gl3. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
_________

gtk-d:gtkd 3.8.4: building configuration "library"...
../../../../.dub/packages/gtk-d-3.8.4/generated/gtkd/gobject/ObjectG.d:204:7: error: template instance hasStaticMember!(T, "getType") template 'hasStaticMember' is not defined
    && hasStaticMember!(T, "getType")

Which gtkd version works with this project?
(I'm on Ubuntu 16.04.)
Cheers

**Comment by trikko** [comment]
Thank you for you report

> WARNING: A deprecated branch based version specification is used for the dependency derelict-sdl2. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
> WARNING: A deprecated branch based version specification is used for the dependency derelict-gl3. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.

This is not a problem. It's a temporary workaround I'm using waiting for fix from third-party :)

> gtk-d:gtkd 3.8.4: building configuration "library"...
> ../../../../.dub/packages/gtk-d-3.8.4/generated/gtkd/gobject/ObjectG.d:204:7: error: template instance hasStaticMember!(T, "getType") template 'hasStaticMember' is not defined
> && hasStaticMember!(T, "getType")

EDIT: I misread the lines above.
I think you're using an old version of dmd, probably installed from 16.04 repository using apt-get install dmd.

Download the latest deb package from here: 
https://dlang.org/download.html#dmd

And install it using:
```
dpkg -i name_of_dmd_package_you_downloaded.deb
```

Or use d-apt repository to keep your dmd updated:

```
sudo wget https://netcologne.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
sudo apt-get update --allow-insecure-repositories && sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring && sudo apt-get update
```

**Comment by whplh** [comment]
Thank you!
It's not your code, but my system dependencies/libraries 

Anyway my issues to get it working:
- do the update explained by trikko
-  had to get SDL2-2.0.9 
- relink/remove old SDL.so
- gtk+ has to be >=2.20 (but beware 2.22 needs glib-2.0 >= 2.49.4 which is 2.48 for xenial packages - 2.20 works fine)

Et voilà. Happy vasing. 

(So for all the fellow Ubuntu 16.04 users coming across this issue: Maybe it's time to do that dist-upgrade ;)
