### ISSUE TITLE
Export is invalid

### ISSUE THREAD

**Issue by WebFreak001** [trikko/vasaro#5]
When I try to load the exported STL file in Cura, it says it's invalid. Also seems broken in Blender.

Attached the generated STL file (compressed)

[vase.zip](https://github.com/trikko/vasaro/files/2675871/vase.zip)

**Comment by trikko** [comment]
Looks fine in simplify3d and meshlab here.
Could you please try the attached version? Does it works?
[vase.zip](https://github.com/trikko/vasaro/files/2676184/vase.zip)

**Comment by WebFreak001** [comment]
that file doesn't work in Blender, nor Cura either

**Comment by trikko** [comment]
Ok now I'm downloading cura

**Comment by trikko** [comment]
Face count was wrong. And:
- Simplify3d works
- Meshlab works
- Cura says "not valid"
- Blender doesn't load anything

Why don't they warn me about "premature end of file"? It would be useful for faster debug and fixing...
